name: unit testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v2
      - name: make
        run: make -C 3_Implementation
=======
    - uses: actions/checkout@v2
    - name: make
      run: make -C 3_Implementation/ test
>>>>>>> ef5d84bdccd2d8f350bf63b86d806fcad3b9da1b
